services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: tmdb_user
      POSTGRES_PASSWORD: tmdb_password
      POSTGRES_DB: tmdb_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmdb_user -d tmdb_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://tmdb_user:tmdb_password@postgres:5432/tmdb_database
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./app:/app
    command: python -m app.database.init_db
    tty: true
    stdin_open: true
    
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - postgres

volumes:
  postgres_data: 